# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GEOMETRY: voyager
  LAYOUT_ID: r9RqJ

tasks:
  default:
    cmds:
    - task: sync
    - task: build

  sync:
    vars:
      METADATA:
        sh: |
          curl --location 'https://oryx.zsa.io/graphql'  \
            --header 'Content-Type: application/json'  \
            --data '{"query":"query getLayout($hashId: String!, $revisionId: String!, $geometry: String) {layout(hashId: $hashId, geometry: $geometry, revisionId: $revisionId) {  revision { hashId, qmkVersion, title }}}","variables":{"hashId":"{{.LAYOUT_ID}}","geometry":"{{.GEOMETRY}}","revisionId":"latest"}}' | jq -c '.data.layout.revision | [.hashId, .qmkVersion, .title]' 
    cmds:
      # TODO require running on main branch
      - git fetch origin main
      - task: pull-oryx
        vars:
          METADATA: '{{.METADATA}}'
      - git merge --no-edit -Xignore-all-space oryx
      - task: qmk-update

  pull-oryx:
    desc: pull latest version of voyager source file
    vars:
      HASH_ID:
        sh: echo '{{.METADATA}}' | jq -r '.[0]' 
      CHANGE_DESC:
        sh: echo '{{.METADATA}}' | jq -r '.[2]' 
      QMK_VERSION:
        sh: echo '{{.METADATA}}' | jq -r '.[1]' | xargs printf "%.0f"
      # TODO stop and ask for worktree creation if missing
      ORYX_WORKTREE_DIR:
        sh: |
           git worktree list --porcelain | \
             grep -a2 heads/oryx | grep -E "^worktree " | awk '{ print $2}'
    dir: '{{.ORYX_WORKTREE_DIR}}'
    cmds:
      - |
          jq -crn \
            --arg hash_id '{{.HASH_ID}}' \
            --arg qmk_version '{{.QMK_VERSION}}' \
            '{hash_id: $hash_id, qmk_version: $qmk_version}' \
            > metadata.json
      - cat metadata.json
      - curl -L "https://oryx.zsa.io/source/{{.HASH_ID}}" -o source.zip
      - unzip -oj source.zip '*_source/*' -d '{{.LAYOUT_ID}}'
      - defer: rm source.zip
      - git add '{{.LAYOUT_ID}}' metadata.json
      - |
          printf "✨(oryx): %s\n" "{{.CHANGE_DESC}}" | git commit -F - || echo "No layout change"

  qmk-update:
    vars:
      QMK_VERSION:
        sh: cat metadata.json | jq -r ".qmk_version"
    cmds:
      - echo 'qmk_version={{.QMK_VERSION}}'
      - git submodule update --init --remote --depth=1 --no-single-branch
      - cd qmk_firmware && git checkout -B firmware{{.QMK_VERSION}} origin/firmware{{.QMK_VERSION}} && git submodule update --init --recursive
      - git add qmk_firmware
      - |
           git commit -m "✨(qmk): Update firmware" || echo "No QMK change"
      
  docker_build:
    cmds:
      - docker build -t qmk .

  qmk-checkout:
    cmds:
      - git submodule update --init --recursive
    
  build:
    deps:
      - docker_build
      - qmk-checkout
    vars:
      DIR: "qmk_firmware/keyboards/zsa/{{.GEOMETRY}}/keymaps"
      normalized_layout_geometry: 
        sh: echo "{{.GEOMETRY}}" | sed 's/\//_/g'
      QMK_VERSION:
        sh: cat metadata.json | jq -r ".qmk_version"
    cmds:
      # Copy layout files to the qmk folder
      - rm -rf {{.DIR}}/{{.LAYOUT_ID}}
      - mkdir -p {{.DIR}} && cp -r {{.LAYOUT_ID}} {{.DIR}}

      # Build the layout
      - docker run -v ./qmk_firmware:/root --rm qmk /bin/sh -c "
          qmk setup zsa/qmk_firmware -b firmware{{.QMK_VERSION}} -y  &&
          make zsa/{{.GEOMETRY}}:{{.LAYOUT_ID}}"

      # Find and export built layout
      - find ./qmk_firmware -maxdepth 1 -type f -name "*{{.normalized_layout_geometry}}*.bin"
